spring:
  datasource:
    url: jdbc:mysql://62.234.35.150:3306/makemoney?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: e2BEZPhnlmgmp@mK
    hikari:
      keepaliveTime: 30000
      maxLifetime: 600000
      maximumPoolSize: 30

feishu:
  appId: cli_a8f2684a097b500c
  appSecret: KOyRW9xuN5fGhU5A2dWScd0XMJ86mhmG

limiter:
  redis:
    host: 62.234.35.150
    port: 6379
    password: HUPf0elbIgAKekBR
    expiration: 180
    prefix: limiter.

config:
  bitables: XGG1blHrkangStsSV82cvhi1n9d
  cron: 0 * * * * ?
